# Generated by Django 4.2.2 on 2023-06-07 18:59

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('icon', models.FileField(upload_to='pwa/icons/', verbose_name='Icon')),
                ('icon_type', models.CharField(choices=[('image/jpeg', 'JPEG/JPG'), ('image/png', 'PNG'), ('image/svg+xml', 'SVG'), ('image/webp', 'WEBP'), ('image/avif', 'AVIF'), ('image/vnd.microsoft.icon', 'ICO')], max_length=25, verbose_name='Icon Type')),
                ('color_scheme', models.CharField(choices=[('Light', 'Light Mode'), ('Dark', 'Dark Mode')], default='Light', max_length=5, verbose_name='Color Scheme')),
                ('sizes', models.CharField(default='any', max_length=250, verbose_name='Sizes')),
                ('purpose', models.CharField(choices=[('monochrome', 'monochrome'), ('maskable', 'maskable'), ('any', 'any')], default='any', max_length=10, verbose_name='Purpose')),
            ],
            options={
                'verbose_name': 'Icon',
                'verbose_name_plural': 'Icons',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('permistion', models.CharField(max_length=150, verbose_name='Permistion Code')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='ProgressiveWebApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=46, verbose_name='Name')),
                ('short_name', models.CharField(max_length=13, verbose_name='Short Name')),
                ('theme_color', models.CharField(max_length=9, verbose_name='Theme Color')),
                ('background_color', models.CharField(max_length=9, verbose_name='Background Color')),
                ('display', models.CharField(choices=[('fullscreen', 'fullscreen'), ('standalone', 'standalone'), ('minimal-ui', 'minimal-ui'), ('browser', 'browser')], max_length=10, verbose_name='Display')),
                ('orientation', models.CharField(choices=[('any', 'any'), ('natural', 'natural'), ('landscape', 'landscape'), ('landscape-primary', 'landscape-primary'), ('landscape-secondary', 'landscape-secondary'), ('portrait', 'portrait'), ('portrait-primary', 'portrait-primary'), ('portrait-secondary', 'portrait-secondary')], max_length=19, verbose_name='Orientation')),
                ('scope', models.SlugField(max_length=100, verbose_name='Scop')),
                ('start_url', models.SlugField(max_length=450, verbose_name='Start URL')),
                ('direction', models.CharField(choices=[('rtl', 'Right to Left'), ('ltr', 'Left to Right')], max_length=3, verbose_name='Direction')),
                ('lang', models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ar-dz', 'Algerian Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('ckb', 'Central Kurdish (Sorani)'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], max_length=50, verbose_name='Language')),
                ('description', models.TextField(verbose_name='Description')),
                ('version', models.CharField(default='1.0.0', max_length=15, verbose_name='Version')),
                ('manifest_version', models.PositiveSmallIntegerField(choices=[(1, 'Vertion 1'), (2, 'Vertion 2'), (3, 'Vertion 3')], default=3, verbose_name='Manifest Version')),
                ('author', models.CharField(max_length=150, verbose_name='Author')),
                ('icons', models.ManyToManyField(related_name='pwa_icons', to='pwa.icons', verbose_name='Icons')),
                ('permissions', models.ManyToManyField(related_name='pwa_permissions', to='pwa.permissions', verbose_name='Permissions')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pwa_site', to='sites.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'PWA',
                'verbose_name_plural': 'PWAs',
            },
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='progressivewebapplication',
            constraint=models.UniqueConstraint(fields=('site',), name='pwa_progressivewebapplication_unique'),
        ),
    ]
